# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  role_name: ssh_daemon_cfg
  author: drew1kun
  description: |
    Cross-platform ansible role for ssh daemon configration.
  license: MIT
  github_branch: main
  min_ansible_version: '2.1'
  platforms:
    - name: Debian
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - ssh
    - sshd
    - secure
    - shell
    - daemon
    - config
dependencies:
  - role: ssh_common
    when: ssh_daemon_cfg_load_common | default(true)
    tags:
      - ssh_daemon_cfg
      - ssh_daemon_cfg_general
      - ssh_daemon_cfg_users
