---
- name: "[revoke.yml] REMOTE: Ensure revoked dir exists on Managed Host"
  ansible.builtin.file:
    path: "{{ ssh_common_etc_dir }}/revoked"
    state: directory
    mode: '0755'
    owner: "{{ ssh_common_owner }}"
    group: "{{ ssh_common_group }}"
  become: true
  notify: Reload sshd

- name: "[revoke.yml] REMOTE: Ensure revoked keys/certs exist on Managed Host"
  ansible.builtin.copy:
    dest: "{{ ssh_common_etc_dir }}/revoked/{{ item.filename }}"
    content: "{{ item.type }} {{ item.b64 | replace(' ', '') }}"
    owner: "{{ ssh_common_owner }}"
    group: "{{ ssh_common_group }}"
    mode: '0644'
  become: true
  notify: Reload sshd
  register: ssh_ca_user_entity_copy
  loop: "{{ ssh_ca_user_crt_revoked }}"
  loop_control:
    label: "{{ item.filename }}"

- name: "[revoke.yml] REMOTE: Revoke the keys/certs"
  ansible.builtin.command: >-
    ssh-keygen -k -f {{ ssh_common_etc_dir }}/{{ ssh_ca_user_krl_filename }}
    -s {{ ssh_common_etc_dir }}/{{ ssh_ca_user__ca.path.split('/')[-1] }}.pub
    -z {{ ssh_ca_user_crt_revoked_item.sn | string }}
    {{ ssh_common_etc_dir }}/revoked/{{ ssh_ca_user_crt_revoked_item.filename }}
  become: true
  notify: Reload sshd
  loop: "{{ ssh_ca_user_crt_revoked }}"
  loop_control:
    loop_var: ssh_ca_user_crt_revoked_item
    label: "{{ ssh_ca_user_crt_revoked_item.filename }}"
  changed_when: ssh_ca_user_entity_copy.changed
