---
- name: "[info.yml] REMOTE: Get newly issued Host Certificate details"
  vars:
    ssh_hostCA_cert_list_cmd: "ssh-keygen -L -f {{ ssh_hostCA_etc_dir }}/ssh_host_{{ ssh_hostCA_key.type|default('ed25519') }}_key-cert.pub"
  ansible.builtin.shell: "{{ item }}"
  register: ssh_hostCA_new_cert
  changed_when: false
  loop:
    - "{{ ssh_hostCA_cert_list_cmd }}"
    - "{{ ssh_hostCA_cert_list_cmd }} | grep 'Serial: ' | xargs | cut -d ' ' -f2 "
  become: true
  when: ssh_hostCA_cert_issued.changed

- name: "[info.yml] INFO: THE CERTIFICATE SERIAL NUMBER HAS CHANGED!"
  debug:
    msg: |
      {{
        'ATTENTION: NEW HOST KEY WAS ISSUED ALONG WITH THE NEW HOST CERTIFICATE.'
        if ssh_hostCA_key_issued.changed else
        'ATTENTION: NEW HOST CERTIFICATE WAS ISSUED FOR THE EXISTING HOST KEY!'
      }}
      SERIAL NUMBER WAS: {{ ssh_hostCA_old_cert_sn.stdout|default('N/A') }}
      SERIAL NUMBER NOW: {{ ssh_hostCA_new_cert.results.1.stdout }}
  when: ssh_hostCA_cert_issued.changed

- name: "[info.yml] INFO: PLEASE MAKE SURE THE PRINCIPALS OF ISSUED CERT ARE CORRECT"
  debug:
    msg: "{{ ssh_hostCA_new_cert.results.0.stdout }}"
  when: ssh_hostCA_cert_issued.changed
