---
galaxy_info:
  role_name: ssh_ca_host
  author: drew1kun
  description: |
    Cross-platform ansible role for hardening ssh daemon configuration,
    by setting up SSH Host Certificate Authentication.
  license: MIT
  min_ansible_version: '1.2'
  github_branch: main
  platforms:
    - name: Debian
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - ssh
    - sshd
    - secure
    - shell
    - user
    - certificates
    - certificate
    - authority
collections:
  - community.crypto
dependencies:
  - role: ssh_common
    when: ssh_ca_host_load_common | default(true)
    tags:
      - ssh_hostCA
      - ssh_hostCA_remote
allow_duplicates: false
