---
## LOCAL SSH CLIENT WORKSTATION TASKS

- name: "[local.yml] LOCAL: Quick OS and user detection"
  ansible.builtin.set_fact:
    ssh_ca_user_local_os: "{{ lookup('pipe', 'uname -s').strip() }}"
    ssh_ca_user_local_user: "{{ lookup('env', 'USER') or lookup('env', 'USERNAME') }}"
  delegate_to: localhost
  run_once: true

- name: "[local.yml] LOCAL: Generate UserCA if it does not exist"
  ansible.builtin.import_role:
    name: ssh_keygen
  delegate_to: localhost
  run_once: true
  vars:
    # must be a list of keys (ssh_ca_user__ca is a map), so:
    ssh_keygen_keys:
      - >-
        {{
          ssh_ca_user__ca | combine({
            'owner': ssh_ca_user_local_user,
            'group': ssh_ca_user_local_user if
            'Darwin' not in ssh_ca_user_local_os else 'staff' })
        }}

- name: "[local.yml] LOCAL: Issue User Certificates"
  community.crypto.openssh_cert:
    type: user
    valid_from: "{{ ssh_ca_user_cert.get('valid_from', 'always') | string }}"
    valid_to: "{{ ssh_ca_user_cert.get('valid_to', 'forever') | string }}"
    signing_key: "{{ ssh_ca_user__ca.get('path') | string }}"
    public_key: "{{ item.1 }}"
    path: "{{ item.1 | regex_replace('\\.pub$', '') }}-cert.pub"
    serial_number: "{{ item.0.sn | int }}"
    principals: "{{ item.0.principal.split(',') | list }}"
    identifier: "{{ item.0.id | string }}"
  delegate_to: localhost
  run_once: true
  register: ssh_ca_user_certs_issued
  # with_nested:
  #  - "{{ ssh_ca_user_cert.principals }}"
  #  - "{{ lookup('fileglob', ssh_ca_user_keys_path+'/*.pub', wantlist=True) }}"
  loop: >-
    {{
      ssh_ca_user_cert.principals
      | product(lookup('fileglob', ssh_ca_user_keys_path+'/*.pub', wantlist=True))
      | list
    }}
  loop_control:
    label: "{{ item.1 }}"
  when:
    - "item.0.user in item.1"
    - "'-cert.pub' not in item.1"

- name: "[local.yml] Flush handlers so cert-related handlers run now"
  ansible.builtin.meta: flush_handlers
  delegate_to: localhost
  run_once: true

# - name: "[local.yml] Send locally generated SSH keypar and Certificate to remote host"
#   ansible.builtin.copy:
#     src: "{{ }}"
#     dest: "{{ ssh_ca_user_cert_path_on_remote|default('~/.ssh') }}"
#   loop: "{{ lookup('fileglob', ssh_ca_user_keys_path+'/*-cert.pub').split(',')|flatten(1) }}"
#   when: ssh_ca_user_cert_send_2_remote | default(false)
#   become: true
#   delegate_to: localhost
#   run_once: true
