---
galaxy_info:
  role_name: ssh_common
  author: drew1kun
  description: |
    Dependency role for ssh_ca_user and ssh_ca_host cross-platform ansible roles.
    Contains common vars and handlers used by the mentioned roles
  license: MIT
  min_ansible_version: '1.2'
  github_branch: main
  platforms:
    - name: Debian
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - ssh
    - sshd
    - secure
    - shell
    - user
    - certificates
    - certificate
    - authority
collections:
  - community.general
allow_duplicates: false
