---
ssh_hostCA_etc_dir: /etc/ssh

# FreeBSD: '/etc/ssh/sshd_config'
# Pfsense: '/etc/sshd_extra';
ssh_hostCA_daemon_config: >-
  '/etc/sshd_extra' if
  (ssh_hostCA_pfsense.results
  | selectattr('stat.exists', 'eq', true)
  | list | length) == 2 else
  '/etc/ssh/sshd_config'
ssh_hostCA_owner: root
ssh_hostCA_group: wheel
