---
- name: 'Reload sshd on Linux'
  ansible.builtin.systemd:
    name: "{{ ssh_userCA_svc_name }}"
    state: reloaded
  listen: Reload sshd
  become: true
  when: "'Linux' in ansible_system"

- name: 'Reload sshd on MacOS'
  community.general.launchd:
    name:  ssh
    state: reloaded
  listen: Reload sshd
  become: true
  when: "'Darwin' in ansible_system"

- name: 'Reload sshd on pfSense'
  ansible.builtin.command: /etc/sshd
  listen: Reload sshd
  become: true
  when: >-
    'FreeBSD' in ansible_system and
    (ssh_userCA_pfsense.results
    | selectattr('stat.exists', 'eq', true)
    | list | length) == 2

- name: 'Reload sshd on FreeBSD'
  ansible.builtin.service:
    name:  sshd
    state: reloaded
  listen: Reload sshd
  become: true
  when: >-
    'FreeBSD' in ansible_system and not
    (ssh_userCA_pfsense.results
    | selectattr('stat.exists', 'eq', true)
    | list | length) == 2
