---
- name: 'Reload sshd on Linux'
  ansible.builtin.systemd:
    name: "{{ ssh_hostCA_svc_name }}"
    state: reloaded
  listen: Reload sshd
  become: true
  when: "'Linux' in ansible_system"

- name: 'Reload sshd on FreeBSD'
  ansible.builtin.command: /etc/sshd
  listen: Reload sshd
  become: true
  when: "'FreeBSD' in ansible_system"

- name: 'Reload sshd on MacOS'
  community.general.launchd:
    name:  ssh
    state: reloaded
  listen: Reload sshd
  become: true
  when: "'Darwin' in ansible_system"
